name: Run Notion Slack Reminder

on:
    schedule:
        - cron: "00 15 * * 1-5" # KST 00:00
    workflow_dispatch: # 수동 실행 가능

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run script
              env:
                  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
                  TIL_NOTION_DATABASE_ID: ${{ secrets.TIL_NOTION_DATABASE_ID }}
                  TIL_SLACK_WEBHOOK_URL: ${{ secrets.TIL_SLACK_WEBHOOK_URL }}
              run: npn run start
